### ISSUE TITLE
Страницы за которыми отвечает Баяман

### ISSUE THREAD

**Issue by Bvivg** [Bvivg/teamexam#2]
Вот следующие страницы и модальные окна:

Страницы:
1. Страница "Пополнение баланса"
2. Страница "Анкета регистрации автора"
3. Страница "Это сообщение появится у автора сразу после нажатия кнопки отправить"

Модальные окна:
1. Фрейм 37

**Comment by BayamanTurdurdumambetov** [comment]
finished
